name: Build SPA

on:
  workflow_call:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache/
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build JS/TS
        run: bun run build

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spa-dist
          path: dist/
          retention-days: 1
