name: Deploy Docker

on:
  workflow_call:
  pull_request:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: spa-dist
          path: dist/

      - name: Build Docker Image
        run: |
          docker build -t bun-spa-app:latest .
